### ISSUE TITLE
Thank you so much for your hard work!

### ISSUE THREAD

**Issue by joseph-abell** [TheoBendixson/Handmade-Hero-MacOS-Platform-Layer-Tutorials#1]
Hi, close this issue when read.

I wanted to say thank you for this amazing resource.

I followed along with Handmade Hero when Casey first started, but unfortunately I ended up moving to a job where my primary machine was a Mac, and my windows machine died suddenly. 

I forgot about the project until a few days ago, and with your help I've got to having controller and keyboard support. It won't be that long until I've caught up with where I was before.

I'll be throwing in some money to your patreon in the coming days.

Thanks again,

Joe

**Comment by TheoBendixson** [comment]
Hey! So happy to have helped out. I plan to do some more YouTube videos on Mac development and the Mac platform layer. 

Also, apologies if some of the changes seem a bit unstructured around Day 020 or so. I more or less followed along with the series, but I wasn't able to get some features working properly on the day Casey built them (for example the live record feature he has on Windows). The platform layer really comes together around Day 026 for me.

Let me know if there's anything in particular you would like me to cover too. I'm thinking I'd like to do rendering on Metal once the series starts doing Open GL rendering, but that's more of a side thing / curiosity.

**Comment by joseph-abell** [comment]
I'm happy to go with wherever you want to take this. As a JS developer by trade, anything low level feels a little bit like magic. But it's been really refreshing working directly with buffers, and I've enjoyed being able to go down some documentation rabbit holes.

The only critique I have had so far is that it has sometimes been a little bit difficult to know where exactly to add new lines of code if I'm following along with the text tutorial alone, but between the videos and the github repository the series as a whole is more than doable. If you want, I'd be happy to throw a few PRs over if I get stuck on something, and it needs a bit of clarification?

**Comment by TheoBendixson** [comment]
Yes, please do and I'll follow up. 

A bit of context. I was spending a lot of time writing articles for each day, only to watch the series for the next day and realize my approach was totally wrong. So I've decided to streamline the educational content and try to get a little further ahead in Casey's series so I know more about what's coming down the road and can therefore better explain it.

I also plan to focus solely on video content, since it really is difficult to sync the article content with the video content. Plus the video content seems to have gotten a better reception from my small audience.

If there is something you would like me to discuss in a video, just let me know and I'll cover it. I generally try to cover the things people ask about, even though I'm not on Twitch and don't "officially" do a Q and A.
